/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package practicaabstractfactory.vistas;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import practicaabstractfactory.componentes.Ford;
import practicaabstractfactory.componentes.Seat;
import practicaabstractfactory.componentes.Toyota;
import practicaabstractfactory.factory.Fabrica;
import practicaabstractfactory.factory.FabricaVehiculoDiesel;
import practicaabstractfactory.factory.FabricaVehiculoHibrido;

/**
 *
 * @author Antonio
 */
public class VistaCrearVehiculoHibrido extends javax.swing.JDialog {
    private ArrayList<Ford> ford;
    private ArrayList<Toyota> toyota;
    private ArrayList<Seat> seat;
    private VistaCatalogo vistaCatalogo;
    /**
     * Creates new form VistaCrearVehiculo
     */
    public VistaCrearVehiculoHibrido(java.awt.Frame parent, boolean modal, ArrayList<Ford> ford, ArrayList<Toyota> toyota, ArrayList<Seat> seat) {
        super(parent, modal);
        initComponents();
        this.ford = ford;
        this.toyota = toyota;
        this.seat = seat;
        String[] nuevosValores = {"Ford", "Toyota", "Seat"};
        marcaCBox.setModel(new DefaultComboBoxModel<>(nuevosValores));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        marcaCBox = new javax.swing.JComboBox<>();
        modeloTxtField = new javax.swing.JTextField();
        cvTxtField = new javax.swing.JTextField();
        autonomiaTxtField = new javax.swing.JTextField();
        consumoTxtField = new javax.swing.JTextField();
        precioTxtField = new javax.swing.JTextField();
        anadirCoche = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        plazasTxtField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Crear vehiculo hibrido:");

        jLabel2.setText("Marca:");

        jLabel3.setText("Modelo:");

        jLabel4.setText("CV:");

        jLabel5.setText("Autonomia electrica:");

        jLabel6.setText("Consumo:");

        jLabel7.setText("Precio:");

        marcaCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        marcaCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcaCBoxActionPerformed(evt);
            }
        });

        modeloTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeloTxtFieldActionPerformed(evt);
            }
        });

        precioTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioTxtFieldActionPerformed(evt);
            }
        });

        anadirCoche.setText("Añadir");
        anadirCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadirCocheActionPerformed(evt);
            }
        });

        jLabel8.setText("Plazas:");

        plazasTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plazasTxtFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(71, 71, 71))
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(precioTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(anadirCoche)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel6)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(consumoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(marcaCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modeloTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cvTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(autonomiaTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(plazasTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(marcaCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(modeloTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(cvTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(autonomiaTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(consumoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(plazasTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(precioTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(anadirCoche)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void marcaCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcaCBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marcaCBoxActionPerformed

    private void anadirCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadirCocheActionPerformed
        try {
            Fabrica fabricaHibrido = new FabricaVehiculoHibrido();

            String marca = (String) marcaCBox.getSelectedItem();
            String modelo = modeloTxtField.getText();
            String tipo = "Hibrido";
            int cv = Integer.parseInt(cvTxtField.getText());
            int consumo = Integer.parseInt(consumoTxtField.getText());
            int autonomiaElectrica = Integer.parseInt(autonomiaTxtField.getText());
            int plazas = Integer.parseInt(plazasTxtField.getText());
            float precio = Float.parseFloat(precioTxtField.getText());
            float cc = 1500f;

            
            switch (marca) {
                case "Ford":
                    Ford nuevoFord = fabricaHibrido.creaFord(modelo, tipo, cv, consumo, autonomiaElectrica, -1, plazas, precio, cc);
                    ford.add(nuevoFord);
                    break;
                case "Toyota":
                    Toyota nuevoToyota = fabricaHibrido.creaToyota(modelo, tipo, cv, consumo, autonomiaElectrica, -1, plazas, precio, cc);
                    toyota.add(nuevoToyota);
                    break;
                case "Seat":
                    Seat nuevoSeat = fabricaHibrido.creaSeat(modelo, tipo, cv, consumo, autonomiaElectrica, -1, plazas, precio, cc);
                    seat.add(nuevoSeat);
                    break;
            }

            javax.swing.JOptionPane.showMessageDialog(this, "Vehículo diésel añadido correctamente.");
            this.dispose();
            vistaCatalogo.setVisible(true);

            modeloTxtField.setText("");
            cvTxtField.setText("");
            consumoTxtField.setText("");
            plazasTxtField.setText("");
            precioTxtField.setText("");

        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, rellena todos los campos numéricos correctamente.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_anadirCocheActionPerformed

    private void modeloTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeloTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modeloTxtFieldActionPerformed

    private void precioTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioTxtFieldActionPerformed

    private void plazasTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plazasTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plazasTxtFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anadirCoche;
    private javax.swing.JTextField autonomiaTxtField;
    private javax.swing.JTextField consumoTxtField;
    private javax.swing.JTextField cvTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JComboBox<String> marcaCBox;
    private javax.swing.JTextField modeloTxtField;
    private javax.swing.JTextField plazasTxtField;
    private javax.swing.JTextField precioTxtField;
    // End of variables declaration//GEN-END:variables
}
