/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package practicaabstractfactory.vistas;

import practicaabstractfactory.componentes.Ford;
import practicaabstractfactory.componentes.Seat;
import practicaabstractfactory.componentes.Toyota;

/**
 *
 * @author Antonio
 */
public class VistaDetalles extends javax.swing.JDialog {

    /**
     * Creates new form VerDetalles
     */
    public VistaDetalles(java.awt.Frame parent, boolean modal, Ford ford, Seat seat, Toyota toyota) {
        super(parent, modal);
        initComponents();
        if (ford != null) {
            modeloTxt.setText("Modelo: " + ford.getModelo());
            tipoTxt.setText("Tipo: " + ford.getTipo());
            cvTxt.setText("CV: " + ford.getCv());
            plazasTxt.setText("Plazas: " + ford.getPlazas());
            precioTxt.setText("Precio: " + ford.getPrecio()+ "€ + " +(ford.getPrecio()*0.3) + "€");
            consumoTxt.setText("Consumo: " + ford.getConsumo());
            autonomiaTxt.setText("Autonomía Eléctrica: " + ford.getAutonomiaElectrica() + "KM");
            recargaTxt.setText("Recarga: " + ford.getRecarga() + "Min");
            ccTxt.setText("CC: " + ford.getCc());
        } else if (seat != null) {
            modeloTxt.setText("Modelo: " + seat.getModelo());
            tipoTxt.setText("Tipo: " + seat.getTipo());
            cvTxt.setText("CV: " + seat.getCv());
            plazasTxt.setText("Plazas: " + seat.getPlazas());
            precioTxt.setText("Precio: " + seat.getPrecio() + "€" );
            consumoTxt.setText("Consumo: " + seat.getConsumo());
            autonomiaTxt.setText("Autonomía Eléctrica: " + seat.getAutonomiaElectrica() + "KM");
            recargaTxt.setText("Recarga: " + seat.getRecarga() + "Min");
            ccTxt.setText("CC: " + seat.getCc());
        } else {
            modeloTxt.setText("Modelo: " + toyota.getModelo());
            tipoTxt.setText("Tipo: " + toyota.getTipo());
            cvTxt.setText("CV: " + toyota.getCv());
            plazasTxt.setText("Plazas: " + toyota.getPlazas());
            precioTxt.setText("Precio: " + toyota.getPrecio() + "¥");
            consumoTxt.setText("Consumo: " + toyota.getConsumo());
            autonomiaTxt.setText("Autonomía Eléctrica: " + toyota.getAutonomiaElectrica() + "KM");
            recargaTxt.setText("Recarga: " + toyota.getRecarga() + "Min");
            ccTxt.setText("CC: " + toyota.getCc());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modeloTxt = new javax.swing.JLabel();
        tipoTxt = new javax.swing.JLabel();
        cvTxt = new javax.swing.JLabel();
        consumoTxt = new javax.swing.JLabel();
        recargaTxt = new javax.swing.JLabel();
        plazasTxt = new javax.swing.JLabel();
        precioTxt = new javax.swing.JLabel();
        autonomiaTxt = new javax.swing.JLabel();
        ccTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        modeloTxt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        modeloTxt.setText("Detalles del modelo:");

        tipoTxt.setText("Tipo:");

        cvTxt.setText("Cv:");

        consumoTxt.setText("Consumo:");

        recargaTxt.setText("Recarga:");

        plazasTxt.setText("Plazas:");

        precioTxt.setText("Precio:");

        autonomiaTxt.setText("Autonomia Electrica:");

        ccTxt.setText("CC:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(modeloTxt)
                .addContainerGap(144, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(autonomiaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(consumoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cvTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tipoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ccTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(precioTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(plazasTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(recargaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(modeloTxt)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoTxt)
                    .addComponent(recargaTxt))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cvTxt)
                    .addComponent(plazasTxt))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consumoTxt)
                    .addComponent(precioTxt))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(autonomiaTxt)
                    .addComponent(ccTxt))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel autonomiaTxt;
    private javax.swing.JLabel ccTxt;
    private javax.swing.JLabel consumoTxt;
    private javax.swing.JLabel cvTxt;
    private javax.swing.JLabel modeloTxt;
    private javax.swing.JLabel plazasTxt;
    private javax.swing.JLabel precioTxt;
    private javax.swing.JLabel recargaTxt;
    private javax.swing.JLabel tipoTxt;
    // End of variables declaration//GEN-END:variables
}
