/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practicaabstractfactory.vistas;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import practicaabstractfactory.componentes.Diesel;
import practicaabstractfactory.componentes.Electrico;
import practicaabstractfactory.componentes.Gasolina;
import practicaabstractfactory.componentes.Hibrido;

/**
 *
 * @author Antonio
 */

public class VistaCatalogo extends javax.swing.JFrame {

    /**
     * Creates new form VistaCatalogo
     */
    public VistaCatalogo(ArrayList<Diesel> diesel, ArrayList<Gasolina> gasolina, ArrayList<Hibrido> hibrido, ArrayList<Electrico> electrico) {
        initComponents();
        String cadenaPrecio;
        float precio;
        String[] columnas = {"Marca", "Tipo", "Modelo", "CV", "Plazas", "Precio", "Ver"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0);

        for (Diesel d : diesel) {
            precio = d.getPrecio();
            if(d.getMarca().equals("Ford")){
                precio = (float) (d.getPrecio() + (d.getPrecio() * 0.3)); //Aplicando aranceles
                cadenaPrecio = precio + "€";
            }else if(d.getMarca().equals("Toyota")){
                cadenaPrecio = precio + "¥";
            }else{
                cadenaPrecio = precio + "€";
            }
            Object[] fila = {d.getMarca(), "Diesel", d.getModelo(), d.getCv(), d.getPlazas(), cadenaPrecio};
            modelo.addRow(fila);
        }

        for (Gasolina g : gasolina) {
            precio = g.getPrecio();
            if(g.getMarca().equals("Ford")){
                precio = (float) (g.getPrecio() + (g.getPrecio() * 0.3)); //Aplicando aranceles
                cadenaPrecio = precio + "€";
            }else if(g.getMarca().equals("Toyota")){
                cadenaPrecio = precio + "¥";
            }else{
                cadenaPrecio = precio + "€";
            }
            Object[] fila = {g.getMarca(), "Gasolina", g.getModelo(), g.getCv(), g.getPlazas(), cadenaPrecio};
            modelo.addRow(fila);
        }

        for (Hibrido h : hibrido) {
            precio = h.getPrecio();
            if(h.getMarca().equals("Ford")){
                precio = (float) (h.getPrecio() + (h.getPrecio() * 0.3)); //Aplicando aranceles
                cadenaPrecio = precio + "€";
            }else if(h.getMarca().equals("Toyota")){
                cadenaPrecio = precio + "¥";
            }else{
                cadenaPrecio = precio + "€";
            }
            Object[] fila = {h.getMarca(), "Híbrido", h.getModelo(), h.getCv(), h.getPlazas(), cadenaPrecio};
            modelo.addRow(fila);
        }

        for (Electrico e : electrico) {
            precio = e.getPrecio();
            if(e.getMarca().equals("Ford")){
                precio = (float) (e.getPrecio() + (e.getPrecio() * 0.3)); //Aplicando aranceles
                cadenaPrecio = precio + "€";
            }else if(e.getMarca().equals("Toyota")){
                cadenaPrecio = precio + "¥";
            }else{
                cadenaPrecio = precio + "€";
            }
            Object[] fila = {e.getMarca(), "Eléctrico", e.getModelo(), e.getCv(), e.getPlazas(), cadenaPrecio};
            modelo.addRow(fila);
        }

        tablaCatalogo.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCatalogo = new javax.swing.JTable();
        anadirVehiculoBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Catalogo coches");

        tablaCatalogo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaCatalogo);

        anadirVehiculoBtn.setText("Añadir vehiculo");
        anadirVehiculoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadirVehiculoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(244, 244, 244))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(anadirVehiculoBtn)
                        .addGap(36, 36, 36))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(anadirVehiculoBtn)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anadirVehiculoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadirVehiculoBtnActionPerformed
        String[] opciones = {"Diesel", "Gasolina", "Híbrido", "Eléctrico"};
        /*Object selectedValue = JOptionPane.showInputDialog(null, //Sacado de aqui -> https://docs.oracle.com/javase/8/docs/api/javax/swing/JOptionPane.html
             "Choose one", "Input",
             JOptionPane.INFORMATION_MESSAGE, null,
             possibleValues, possibleValues[0]);*/
        String seleccion = (String) JOptionPane.showInputDialog(this, "Que tipo de vehiculo quieres añadir", "Selecciona uno",
                                    JOptionPane.QUESTION_MESSAGE, null, 
                                    opciones, opciones[0]);
        if(seleccion.equals("Diesel")){
            VistaCrearVehiculoDiesel vistaDiesel = new VistaCrearVehiculoDiesel(this, true);
            vistaDiesel.setVisible(true);
        }else if(seleccion.equals("Gasolina")){
            VistaCrearVehiculoGasolina vistaGasolina = new VistaCrearVehiculoGasolina(this, true);
            vistaGasolina.setVisible(true);
        }else if(seleccion.equals("Híbrido")){
            VistaCrearVehiculoHibrido vistaHibrido = new VistaCrearVehiculoHibrido(this, true);
            vistaHibrido.setVisible(true);
        }else{
            VistaCrearVehiculoElectrico vistaElectrico = new VistaCrearVehiculoElectrico(this, true);
            vistaElectrico.setVisible(true);
        }
    }//GEN-LAST:event_anadirVehiculoBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anadirVehiculoBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCatalogo;
    // End of variables declaration//GEN-END:variables
}
