/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practica1.Vista;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import practica1.Controlador.ControladorUsuario;
import practica1.Modelo.Agencia;
import practica1.Modelo.Avion;
import practica1.Modelo.Usuario;

/**
 *
 * @author Antonio
 */
public class VistaAvion extends javax.swing.JFrame {
    
    ControladorUsuario controlador;
    private Usuario usuario;
    private Agencia agencia;
    private Avion avion;

    public VistaAvion(Usuario usuario, ControladorUsuario controlador) {
        this.controlador = controlador;
        this.usuario = usuario;
        this.agencia = new Agencia();
        setSize(400, 350);
        initComponents();
        infoLabel.setText("Asientos disponibles: " + avion.cuantosAsientosQuedan());
        billetesUsuarioTxtField.setText("Billetes del usuario: "+ usuario.getnBilletes());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        devolverBilletesBtn = new javax.swing.JButton();
        comprarBilletesBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        infoLabel = new javax.swing.JLabel();
        billetesUsuarioTxtField = new javax.swing.JLabel();
        cerrarSesionBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 200));

        devolverBilletesBtn.setText("Devolver billetes");
        devolverBilletesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devolverBilletesBtnActionPerformed(evt);
            }
        });

        comprarBilletesBtn.setText("Comprar billetes");
        comprarBilletesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarBilletesBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("¿Que desea realizar?");

        infoLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        infoLabel.setText("Asientos disponibles: ");

        billetesUsuarioTxtField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        billetesUsuarioTxtField.setText("Billetes del usuario:");

        cerrarSesionBtn.setText("Cerrar sesión");
        cerrarSesionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(infoLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(devolverBilletesBtn)
                                .addGap(18, 18, 18)
                                .addComponent(comprarBilletesBtn))
                            .addComponent(billetesUsuarioTxtField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cerrarSesionBtn)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cerrarSesionBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(billetesUsuarioTxtField)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comprarBilletesBtn)
                    .addComponent(devolverBilletesBtn))
                .addGap(18, 18, 18)
                .addComponent(infoLabel)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void devolverBilletesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devolverBilletesBtnActionPerformed
        String input = JOptionPane.showInputDialog(this, "¿Cuántos billetes deseas devolver?");
        int cantidad = Integer.parseInt(input);
        boolean exito = agencia.quieroDevolverBilletes(usuario, cantidad);
        if (exito) {
            JOptionPane.showMessageDialog(this, "Billetes devueltos correctamente.");
        } else {
            JOptionPane.showMessageDialog(this, "Número no válido.");
        }
        infoLabel.setText("Asientos disponibles: " + avion.cuantosAsientosQuedan());
        billetesUsuarioTxtField.setText("Billetes del usuario: "+ usuario.getnBilletes());
    }//GEN-LAST:event_devolverBilletesBtnActionPerformed

    private void comprarBilletesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarBilletesBtnActionPerformed
        String input = JOptionPane.showInputDialog(this, "¿Cuántos billetes deseas comprar?");
        int cantidad = Integer.parseInt(input);
        boolean exito = usuario.quieroComprarBilletes(cantidad);
        if (exito) {
            JOptionPane.showMessageDialog(this, "Compra realizada con éxito.");
        } else {
            JOptionPane.showMessageDialog(this, "No hay suficientes asientos disponibles.");
        }
        infoLabel.setText("Asientos disponibles: " + avion.cuantosAsientosQuedan());
        billetesUsuarioTxtField.setText("Billetes del usuario: "+ usuario.getnBilletes());
    }//GEN-LAST:event_comprarBilletesBtnActionPerformed

    private void cerrarSesionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionBtnActionPerformed
        this.controlador.cerrarSesion();
    }//GEN-LAST:event_cerrarSesionBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel billetesUsuarioTxtField;
    private javax.swing.JButton cerrarSesionBtn;
    private javax.swing.JButton comprarBilletesBtn;
    private javax.swing.JButton devolverBilletesBtn;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
